// <auto-generated />
namespace PhotoKingdomAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removecountryidincity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecountryidincity));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181932429_remove-countryid-in-city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
