// <auto-generated />
namespace PhotoKingdomAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgpscoordinatestoping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgpscoordinatestoping));
        
        string IMigrationMetadata.Id
        {
            get { return "201804161432457_add-gps-coordinates-to-ping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
