// <auto-generated />
namespace PhotoKingdomAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adduniquekeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduniquekeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201802252118534_add-unique-keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
