// <auto-generated />
namespace PhotoKingdomAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removecascadecycles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecascadecycles));
        
        string IMigrationMetadata.Id
        {
            get { return "201802110508246_remove-cascade-cycles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
